# Local Quarkus Application Configuration in YAML format
# This file is intended for local development overrides.

quarkus:
  banner:
    path: banner.txt
  log:
    level: DEBUG # Often set to DEBUG for local development
    console:
      level: DEBUG

# Override Bitcoin RPC Configuration for local node
bitcoin:
  rpc:
    host: bitcoin.hjacquot.xyz
    port: 443 # Default Bitcoin Core RPC port
    user: hadrien
    password: tZxpjg-IuvuAAoGPJCrPhvFK4Z99dqvq49IO7BVk9aA
    scheme: https

dashboard:
  polling:
    interval:
      seconds: ${WS_POLLING_INTERVAL:1}
  health:
    min:
      outbound:
        peers: ${MIN_OUTBOUND_PEERS:8}
